//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintingHouseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ContractId { get; set; }
        public int ProductId { get; set; }
        public int ProductAmount { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Product Product { get; set; }
    }
}
