//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintingHouseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdInContract
    {
        public int ContractId { get; set; }
        public string CustomerName { get; set; }
        public string Name { get; set; }
        public decimal PricePerPiece { get; set; }
        public int ProductAmount { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
